<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'name' => 'Administrator',
                'username' => 'admin',
                'username_verified_at' => now(),
                'password' => Hash::make('admin'),
                'role' => 'administrator',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Koordinator',
                'username' => 'koordinator',
                'username_verified_at' => now(),
                'password' => Hash::make('koor'),
                'role' => 'koordinator',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Susatyo N W P., ST, MM',
                'username' => '196903111997021000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rani Rumita,. ST,MT',
                'username' => '197311061998022000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr.Ir.B. Purwanggono,M.Eng.',
                'username' => '195704221986031000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Prof. Dr. Aries Susanty, ST.MT',
                'username' => '197103271999032000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr.Ir. Heru Prastawa, DEA',
                'username' => '196003151987031000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr.Denny Nurkertamanda,ST.MT',
                'username' => '197312211999031000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr.Ir.KRMT.Haryo Santoso.,MM',
                'username' => '195007221986031000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr.Purnawan Adi. W, ST.MT',
                'username' => '197710032000031000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Ratna Purwaningsih, ST,MT',
                'username' => '197212311998022000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zainal Fanani Rosyada. ST.,MT',
                'username' => '197105152000031000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. rer.oec.Arfan B, ST.MT',
                'username' => '197503062000121000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Darminto Pujotomo, ST.MT',
                'username' => '197404262000121000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sriyanto, ST.MT',
                'username' => '197409122000121000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr.Singgih Saptadi, ST.MT',
                'username' => '197403162001121000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Hery Suliantoro,ST.MT',
                'username' => '196904292002121000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sri Hartini, ST.MT',
                'username' => '197006252002122000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Naniek Utami H., S.Si,MT',
                'username' => '197305072002122000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Diana Puspitasari, ST.MT',
                'username' => '197902192003122000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ary Arvianto, ST.MT',
                'username' => '198109132003121000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Ing.Novie S, ST,M.Eng',
                'username' => '198211072005012000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dyah Ika Rinawati, ST.MT',
                'username' => '198403262006042000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nia Budi Puspitasari, ST.MT',
                'username' => '198402172006042000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wiwik Budiawan. ST.MT',
                'username' => '198603192012121000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yusuf Widharto, ST, M.Eng',
                'username' => '198010272015041000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr.A.A.S Manik M.J.M,ST,MSc',
                'username' => '198305032010122000',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'dosen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mohammad Ferry Maghriza Pasya',
                'username' => '21070117110001',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muhammad Hafidz Al Huda',
                'username' => '21070117110002',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pandu Adhyaksa',
                'username' => '21070117110003',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ignatius Jeffry Sabaraya',
                'username' => '21070117110004',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muhammad Arrachman N.A.N',
                'username' => '21070117110005',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rifqi Afiq Taib',
                'username' => '21070117120006',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Atheea Annisa Rahma',
                'username' => '21070117120007',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rheza Aulia Ramadhan',
                'username' => '21070117120008',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aradita Anisya Permata',
                'username' => '21070117120009',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mutiara Adhilia Purwaningsih',
                'username' => '21070117120010',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ramandhika Alief Nurahayu P',
                'username' => '21070117120011',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Avinda Jihan Ardiani',
                'username' => '21070117120012',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yosefin Mahanani',
                'username' => '21070117120013',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Raka Pandhito Bagja',
                'username' => '21070117120014',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aprilia Dwi Lestari',
                'username' => '21070117120015',
                'username_verified_at' => now(),
                'password' => Hash::make('000000'),
                'role' => 'mahasiswa',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
